# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MANTY/BlackboardSynth_MANTIS/synth_modules/programmable_synth_core/programmable_synth_core.srcs/sources_1/bd/mantis_synth/ip/mantis_synth_auto_pc_0/mantis_synth_auto_pc_0.xci
# IP: The module: 'mantis_synth_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MANTY/BlackboardSynth_MANTIS/synth_modules/programmable_synth_core/programmable_synth_core.gen/sources_1/bd/mantis_synth/ip/mantis_synth_auto_pc_0/mantis_synth_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mantis_synth_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/MANTY/BlackboardSynth_MANTIS/synth_modules/programmable_synth_core/programmable_synth_core.srcs/sources_1/bd/mantis_synth/ip/mantis_synth_auto_pc_0/mantis_synth_auto_pc_0.xci
# IP: The module: 'mantis_synth_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MANTY/BlackboardSynth_MANTIS/synth_modules/programmable_synth_core/programmable_synth_core.gen/sources_1/bd/mantis_synth/ip/mantis_synth_auto_pc_0/mantis_synth_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mantis_synth_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
