# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Libraries/Documents/School/MANTY/BlackboardSynth_MANTIS/synth_modules/MANTIS_synth_constraint.xdc

# Block Designs: bd/mantis_synth/mantis_synth.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth || ORIG_REF_NAME==mantis_synth} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_processing_system7_0_0/mantis_synth_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_processing_system7_0_0 || ORIG_REF_NAME==mantis_synth_processing_system7_0_0} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_xbar_0/mantis_synth_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_xbar_0 || ORIG_REF_NAME==mantis_synth_xbar_0} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_ps7_0_axi_periph_0/mantis_synth_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_ps7_0_axi_periph_0 || ORIG_REF_NAME==mantis_synth_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_rst_ps7_0_50M_0/mantis_synth_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_rst_ps7_0_50M_0 || ORIG_REF_NAME==mantis_synth_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_mantis_synth_0_0/mantis_synth_mantis_synth_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_mantis_synth_0_0 || ORIG_REF_NAME==mantis_synth_mantis_synth_0_0} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_mantis_synth_1_3/mantis_synth_mantis_synth_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_mantis_synth_1_3 || ORIG_REF_NAME==mantis_synth_mantis_synth_1_3} -quiet] -quiet

# IP: bd/mantis_synth/ip/mantis_synth_auto_pc_0/mantis_synth_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mantis_synth_auto_pc_0 || ORIG_REF_NAME==mantis_synth_auto_pc_0} -quiet] -quiet

# XDC: d:/Libraries/Documents/School/MANTY/BlackboardSynth_MANTIS/synth_modules/programmable_synth_platform/programmable_synth_platform.gen/sources_1/bd/mantis_synth/mantis_synth_ooc.xdc
